name: final20250112
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  excel: ^2.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/clashroyale.xlsx
    - assets/img/
    - assets/img/皇室戰爭手機圖標.png
    - assets/img/皇室卡牌資訊/傳奇卡/公主.png
    - assets/img/皇室卡牌資訊/傳奇卡/哥布林機甲.png
    - assets/img/皇室卡牌資訊/傳奇卡/地獄飛龍.png
    - assets/img/皇室卡牌資訊/傳奇卡/女巫姥姥.png
    - assets/img/皇室卡牌資訊/傳奇卡/寒冰法師.png
    - assets/img/皇室卡牌資訊/傳奇卡/幻影刺客.png
    - assets/img/皇室卡牌資訊/傳奇卡/掘地礦工.png
    - assets/img/皇室卡牌資訊/傳奇卡/暗夜女巫.png
    - assets/img/皇室卡牌資訊/傳奇卡/滾木.png
    - assets/img/皇室卡牌資訊/傳奇卡/漁大師.png
    - assets/img/皇室卡牌資訊/傳奇卡/熔岩獵犬.png
    - assets/img/皇室卡牌資訊/傳奇卡/狂暴伐木工.png
    - assets/img/皇室卡牌資訊/傳奇卡/皇家幽靈.png
    - assets/img/皇室卡牌資訊/傳奇卡/神箭射手.png
    - assets/img/皇室卡牌資訊/傳奇卡/蠻羊騎士.png
    - assets/img/皇室卡牌資訊/傳奇卡/超級騎士.png
    - assets/img/皇室卡牌資訊/傳奇卡/閃電法師.png
    - assets/img/皇室卡牌資訊/傳奇卡/電磁炮.png
    - assets/img/皇室卡牌資訊/傳奇卡/骷髏召喚.png
    - assets/img/皇室卡牌資訊/傳奇卡/鳳凰.png
    - assets/img/皇室卡牌資訊/史詩卡/X連弩.png
    - assets/img/皇室卡牌資訊/史詩卡/冰凍法術.png
    - assets/img/皇室卡牌資訊/史詩卡/加農炮戰車.png
    - assets/img/皇室卡牌資訊/史詩卡/哥布林巨人.png
    - assets/img/皇室卡牌資訊/史詩卡/哥布林詛咒.png
    - assets/img/皇室卡牌資訊/史詩卡/哥布林鑽地機.png
    - assets/img/皇室卡牌資訊/史詩卡/哥布林飛桶.png
    - assets/img/皇室卡牌資訊/史詩卡/女巫.png
    - assets/img/皇室卡牌資訊/史詩卡/巨石投手.png
    - assets/img/皇室卡牌資訊/史詩卡/戈侖石人.png
    - assets/img/皇室卡牌資訊/史詩卡/攻城炸彈人.png
    - assets/img/皇室卡牌資訊/史詩卡/旋風法術.png
    - assets/img/皇室卡牌資訊/史詩卡/毒藥法術.png
    - assets/img/皇室卡牌資訊/史詩卡/氣球兵.png
    - assets/img/皇室卡牌資訊/史詩卡/狂暴法術.png
    - assets/img/皇室卡牌資訊/史詩卡/獵人.png
    - assets/img/皇室卡牌資訊/史詩卡/王子.png
    - assets/img/皇室卡牌資訊/史詩卡/皮卡超人.png
    - assets/img/皇室卡牌資訊/史詩卡/符文巨人.png
    - assets/img/皇室卡牌資訊/史詩卡/虛空法術.png
    - assets/img/皇室卡牌資訊/史詩卡/複製法術.png
    - assets/img/皇室卡牌資訊/史詩卡/野蠻人滾桶.png
    - assets/img/皇室卡牌資訊/史詩卡/鏡像法術.png
    - assets/img/皇室卡牌資訊/史詩卡/閃電巨人.png
    - assets/img/皇室卡牌資訊/史詩卡/雷電法術.png
    - assets/img/皇室卡牌資訊/史詩卡/雷電飛龍.png
    - assets/img/皇室卡牌資訊/史詩卡/飛斧屠夫.png
    - assets/img/皇室卡牌資訊/史詩卡/飛龍寶寶.png
    - assets/img/皇室卡牌資訊/史詩卡/骷髏守衛.png
    - assets/img/皇室卡牌資訊/史詩卡/骷髏巨人.png
    - assets/img/皇室卡牌資訊/史詩卡/骷髏軍團.png
    - assets/img/皇室卡牌資訊/史詩卡/黑暗王子.png
    - assets/img/皇室卡牌資訊/普通卡/亡靈.png
    - assets/img/皇室卡牌資訊/普通卡/亡靈大軍.png
    - assets/img/皇室卡牌資訊/普通卡/冰雪精靈.png
    - assets/img/皇室卡牌資訊/普通卡/加農炮.png
    - assets/img/皇室卡牌資訊/普通卡/哥布林.png
    - assets/img/皇室卡牌資訊/普通卡/哥布林大隊.png
    - assets/img/皇室卡牌資訊/普通卡/哥布林投茅手.png
    - assets/img/皇室卡牌資訊/普通卡/巨型雪球.png
    - assets/img/皇室卡牌資訊/普通卡/弓箭手.png
    - assets/img/皇室卡牌資訊/普通卡/惡棍小隊.png
    - assets/img/皇室卡牌資訊/普通卡/炸彈兵.png
    - assets/img/皇室卡牌資訊/普通卡/烈焰精靈.png
    - assets/img/皇室卡牌資訊/普通卡/煙火射手.png
    - assets/img/皇室卡牌資訊/普通卡/特斯拉電磁塔.png
    - assets/img/皇室卡牌資訊/普通卡/皇家巨人.png
    - assets/img/皇室卡牌資訊/普通卡/皇家快遞.png
    - assets/img/皇室卡牌資訊/普通卡/皇家衛隊.png
    - assets/img/皇室卡牌資訊/普通卡/精銳野蠻人.png
    - assets/img/皇室卡牌資訊/普通卡/萬箭齊發.png
    - assets/img/皇室卡牌資訊/普通卡/蝙蝠.png
    - assets/img/皇室卡牌資訊/普通卡/迫擊炮.png
    - assets/img/皇室卡牌資訊/普通卡/野蠻人.png
    - assets/img/皇室卡牌資訊/普通卡/閃電精靈.png
    - assets/img/皇室卡牌資訊/普通卡/雷電精靈.png
    - assets/img/皇室卡牌資訊/普通卡/電擊法術.png
    - assets/img/皇室卡牌資訊/普通卡/騎士.png
    - assets/img/皇室卡牌資訊/普通卡/骷髏兵.png
    - assets/img/皇室卡牌資訊/普通卡/骷髏氣球.png
    - assets/img/皇室卡牌資訊/普通卡/骷髏飛龍.png
    - assets/img/皇室卡牌資訊/稀有卡/三個火槍手.png
    - assets/img/皇室卡牌資訊/稀有卡/可疑草叢.png
    - assets/img/皇室卡牌資訊/稀有卡/吹箭哥布林.png
    - assets/img/皇室卡牌資訊/稀有卡/哥布林小屋.png
    - assets/img/皇室卡牌資訊/稀有卡/哥布林爆破狂.png
    - assets/img/皇室卡牌資訊/稀有卡/哥布林牢籠.png
    - assets/img/皇室卡牌資訊/稀有卡/地獄之塔.png
    - assets/img/皇室卡牌資訊/稀有卡/地震法術.png
    - assets/img/皇室卡牌資訊/稀有卡/巨人.png
    - assets/img/皇室卡牌資訊/稀有卡/戈侖冰人.png
    - assets/img/皇室卡牌資訊/稀有卡/戰爭天使.png
    - assets/img/皇室卡牌資訊/稀有卡/治療精靈.png
    - assets/img/皇室卡牌資訊/稀有卡/法師.png
    - assets/img/皇室卡牌資訊/稀有卡/火槍手.png
    - assets/img/皇室卡牌資訊/稀有卡/火球.png
    - assets/img/皇室卡牌資訊/稀有卡/火箭.png
    - assets/img/皇室卡牌資訊/稀有卡/炸彈塔.png
    - assets/img/皇室卡牌資訊/稀有卡/烈焰熔爐.png
    - assets/img/皇室卡牌資訊/稀有卡/瓦基麗武神.png
    - assets/img/皇室卡牌資訊/稀有卡/皇家野豬.png
    - assets/img/皇室卡牌資訊/稀有卡/聖水戈侖.png
    - assets/img/皇室卡牌資訊/稀有卡/聖水收集器.png
    - assets/img/皇室卡牌資訊/稀有卡/迷你皮卡.png
    - assets/img/皇室卡牌資訊/稀有卡/重甲亡靈.png
    - assets/img/皇室卡牌資訊/稀有卡/野蠻人小屋.png
    - assets/img/皇室卡牌資訊/稀有卡/野蠻人攻城槌.png
    - assets/img/皇室卡牌資訊/稀有卡/野豬騎士.png
    - assets/img/皇室卡牌資訊/稀有卡/電擊車小隊.png
    - assets/img/皇室卡牌資訊/稀有卡/飛行器.png
    - assets/img/皇室卡牌資訊/稀有卡/骷髏墓碑.png
    - assets/img/皇室卡牌資訊/英雄卡/哥布林科學怪.png
    - assets/img/皇室卡牌資訊/英雄卡/威猛礦工.png
    - assets/img/皇室卡牌資訊/英雄卡/小王子.png
    - assets/img/皇室卡牌資訊/英雄卡/弓箭女皇.png
    - assets/img/皇室卡牌資訊/英雄卡/絕世武僧.png
    - assets/img/皇室卡牌資訊/英雄卡/金甲騎士.png
    - assets/img/皇室卡牌資訊/英雄卡/骷髏之王.png
